Remove `d_prototype` & create type tests for `p_prototype`
SKopecz/PositiveIntegrators.jl pull request #104
Opened 2024-07-17 20:04 UTC by SKopecz

1. There is no need for a `d_prototype`, see the discussion in #99. In the algorithm caches we simply use `D=similar(u)` etc. A `PDSFunction` still has a field `d_protoype` which is initialized as  `d_protoype=similar(u0)`, but users cannot change this or pass `d_protoype` as a keyword to a `PDSProblem`.
2. An additional test ensures that the `P`s in the algorithm caches have the same type as given `p_prototype` (only for in-place)

2024-07-17 20:10 UTC, SKopecz commented
Does the version change to v0.2.0?

2024-07-18 06:22 UTC, ranocha commented
> Does the version change to v0.2.0?

Yes - this is a breaking change, so we have to increment the leading non-zero digit of the version number. We should also add something like

```
## Changes when updating to v0.2 from v0.1.x

#### Added

#### Changed

#### Deprecated

#### Removed

- The optional keyword argument `d_prototype` has been removed from `PDSProblem`
```

to NEWS.md

2024-07-18 06:24 UTC, ranocha requested changes
Thanks! Could you please increment the version number and describe the changes in NEWS.md?

2024-07-18 06:24 UTC, ranocha commented on test/runtests.jl
> +        # dense vectors
```suggestion
        # We test sparse, tridiagonal, and dense matrices.
```

2024-07-18 13:27 UTC, SKopecz commented
This should now be ready to merge.

2024-07-18 14:05 UTC, ranocha commented
Thanks! I would like to merge #105 first, release a new version of PositiveIntegrators.jl, and merge this PR afterwards

2024-07-18 17:45 UTC, ranocha approved these changes

2024-07-18 17:45 UTC, merged